[theme]
primaryColor = "#1E7D4E"          # vert principal (boutons, liens)
backgroundColor = "#F7FAF7"       # fond clair
secondaryBackgroundColor = "#E8F2EC"  # panneaux/cartes
textColor = "#102018"             # texte foncé (lisible)
font = "sans serif"
